context.properties = {
    # Default clock rate and allowed rates for REAPER / Pro Audio
    default.clock.rate          = 48000
    default.clock.allowed-rates = [ 44100 48000 ]

    # Default quantum (buffer size) in samples (256 @ 48kHz = 5.3ms)
    default.clock.quantum       = 256

    # Dynamic limits for CS2 / Low Latency (min 64 = 1.3ms) and Heavy mixing (max 2048 = 42.6ms)
    default.clock.min-quantum   = 64
    default.clock.max-quantum   = 2048
}
